### ISSUE TITLE
Assertion failed: (yytypeid_), function as, file /Users/jva/work/Retro68-build/build-host/Rez/RezParser.generated.hh, line 370.

### ISSUE THREAD

**Issue by Hackintosh42** [autc04/Retro68#72] opened 2018-12-23 03:05 UTC
Hi Wolfgang, thanks so much for the patch that solved the bison RezParzer error yesterday,  it seems so close now, just encountered this error as it tries to compile the console test, not sure if it is some how related?

Error encountered on Mac OS X Mojave 10.14 
```
Scanning dependencies of target ConsoleTest
[ 19%] Building CXX object Console/CMakeFiles/ConsoleTest.dir/ConsoleTest.cc.obj
[ 20%] Linking CXX executable ConsoleTest.code.bin
[ 20%] Built target ConsoleTest
Scanning dependencies of target ConsoleTest_APPL
[ 21%] Generating ConsoleTest.bin, ConsoleTest.APPL, ConsoleTest.dsk, ConsoleTest.ad, %ConsoleTest.ad
Assertion failed: (yytypeid_), function as, file /Users/jva/work/Retro68-build/build-host/Rez/RezParser.generated.hh, line 370.
/bin/sh: line 1: 34988 Abort trap: 6           /Users/jva/work/Retro68-build/build-host/Rez/Rez /Users/jva/work/Retro68/libretro/Retro68APPL.r -I/Users/jva/work/Retro68/libretro:/Users/jva/work/Retro68-build/toolchain/m68k-apple-macos/RIncludes --copy ConsoleTest.code.bin -o ConsoleTest.bin -t APPL -c ???? --cc ConsoleTest.dsk --cc ConsoleTest.APPL --cc %ConsoleTest.ad
make[2]: *** [Console/ConsoleTest.bin] Error 134
make[1]: *** [Console/CMakeFiles/ConsoleTest_APPL.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by autc04** [comment] 2018-12-23 10:11
Okay, yes that's related.
Bison 3.2 sucks. I'll have to figure out a way to work around their broken "modern"[1] C++ code without breaking compatibility with bison 3.0 (as it will take some time until bison 3.2 is conveniently available everywhere...)


[1] C++11 and later put another set of very cool and very sharp tools into everyone's hands. They can be used correctly, to write libraries and APIs that "just work". Or they can be used badly, cutting innocent people. Bison 3.2 does the latter.

**Comment by autc04** [comment] 2018-12-23 11:03
Luckily, there *is* a workaround.
(and the fix in bison will be a single-line fix, too, so all is well)

**Comment by Hackintosh42** [comment] 2018-12-25 04:19
is there any way to downgrade to bison 3.0 on os x with brew?

**Comment by autc04** [comment] 2018-12-25 19:04
Downgrading: only if you previously had bison 3.0.5 installed (`brew switch bison 3.0.5`).
Rather than downgrading, I recommend upgrading.
A bugfix for Bison was released yesterday (bison 3.2.4), and today, there is already a pull request for homebrew (https://github.com/Homebrew/homebrew-core/pull/35444).

Not long from now, you'll be able to write `brew upgrade bison` and the problem will go away.

**Comment by Hackintosh42** [comment] 2018-12-26 11:30
Awesome with the Bison update, and your new code it is compiling now,
I notice that that the .APPL is at 0Bytes, I suppose this is normal if one
compiles 68K programs on Mac OS Mojave?

**Comment by autc04** [comment] 2018-12-26 14:00
The .APPL should have 0 bytes in the data fork, but more than that in the resource fork. The Finder should show a non-zero size, but the `ls -l` command will report 0 bytes.

**Comment by WartyMN** [comment] 2018-12-28 16:34
I now this was closed, but I get this error with Bison 3.2.4 on a build today: 
----
-- Build files have been written to: /Users/XXXXX/Documents/Classic_Computers/Mac_dev/Retro68v2/Retro68-build/build-target
[ 13%] Built target retrocrt
[ 17%] Built target RetroConsole
[ 20%] Built target ConsoleTest
[ 21%] Generating ConsoleTest.bin, ConsoleTest.APPL, ConsoleTest.dsk, ConsoleTest.ad, %ConsoleTest.ad
**Assertion failed: (yytypeid_), function as, file /Users/XXXXX/Documents/Classic_Computers/Mac_dev/Retro68v2/Retro68-build/build-host/Rez/RezParser.generated.hh, line 370.**
/bin/sh: line 1: 39377 Abort trap: 6           /Users/XXXXX/Documents/Classic_Computers/Mac_dev/Retro68v2/Retro68-build/build-host/Rez/Rez /Users/XXXXX/Documents/Classic_Computers/Mac_dev/Retro68v2/Retro68-master/libretro/Retro68APPL.r -I/Users/XXXXX/Documents/Classic_Computers/Mac_dev/Retro68v2/Retro68-master/libretro:/Users/XXXXX/Documents/Classic_Computers/Mac_dev/Retro68v2/Retro68-build/toolchain/m68k-apple-macos/RIncludes --copy ConsoleTest.code.bin -o ConsoleTest.bin -t APPL -c ???? --cc ConsoleTest.dsk --cc ConsoleTest.APPL --cc %ConsoleTest.ad
gmake[2]: *** [Console/CMakeFiles/ConsoleTest_APPL.dir/build.make:61: Console/ConsoleTest.bin] Error 134
gmake[1]: *** [CMakeFiles/Makefile2:150: Console/CMakeFiles/ConsoleTest_APPL.dir/all] Error 2
gmake: *** [Makefile:141: all] Error 2
-----

**Comment by autc04** [comment] 2018-12-28 23:35
This does indeed look like the exact same problem. Could you first make absolutely sure that there aren't some leftovers from the buggy version in your build?

For example, try:

    cd build-host
    make clean
    make
    make install
    cd ../build-target
    make

**Comment by autc04** [comment] 2019-01-02 20:06
@WartyMN any updates? Can I close this again?

**Comment by WartyMN** [comment] 2019-01-03 01:00
Sorry for late reply. I did a new install, and it ran clean, so I think your fix was good from the beginning. 

Do you want me to file one about the /opt/local (mac ports) question? It's not a bug per se. I comment out the /opt/local bits every time I update, but I don't know if anyone else still has mac ports stuff they have been dragging around. Happy to file it though if it would help.

**Comment by autc04** [comment] 2019-01-03 01:05
No problem, thanks!

Feel free to file an issue about the MacPorts thing. That was added not too long ago because someone is still using MacPorts. If we have a ticket, we can discuss the proper way to handle it there.

**Closed by autc04** 2019-01-03 01:05 UTC
