### ISSUE TITLE
Support for older System versions

### ISSUE THREAD

**Issue by mdanh2002** [autc04/Retro68#22] opened 2017-03-24 04:39 UTC
Works great for System 6 and above when using with MPW 3.5 files. However, I tried to run the compiled app on Mac OS 3.2 (Finder 5.3) and got the message "A system error has occurred" with "ID = 10" which indicates that the app attempts to access a non-existent ROM routine or something like that. This happens even if the app only contains a single return; in the main() method, so i guess the problem is somewhere inside the bundled libraries that are meant for newer System versions. 

Do you know what to change to make it work with earlier System versions? I am trying to use the Macintosh Programmer Workshop 1.1 files to make it work with older System versions.

**Comment by autc04** [comment] 2017-03-24 07:58
This is probably the call to `SysEnviron` in `libretro/relocate.c`, line 204. I think the calls above it should be fine, but I haven't checked. I believe there is some traditional sequence for figuring out whether SysEnviron exists, I just didn't bother.

Patches are welcome. Just be careful not to call any functions (except traps) or access any global variables in that code.

**Comment by mdanh2002** [comment] 2017-03-24 08:12
Thanks for the fast reply. Another observation is that if the generated application from Retro68 is run on a Macintosh 512Ke (which has 512K of RAM but with a Macintosh Plus ROM) with Mac OS 3.2 and Finder 5.3, the app also crashed but with a different error code - it now shows ID = 12 (Unimplemented Core Routine), which according to http://www.macwizard.com/errors.html means that a debug breakpoint is triggered somewhere. If the app is run on a Macintosh 512K (original ROM) with System 3.2, then ID = 10 is shown. 

I am still investigating and will update again if I manage to get it to work using your suggestions.

**Comment by autc04** [comment] 2017-03-24 14:00
Error 10 is the unimplemented A-Trap error.
This might be the call to SysEnviron, or now that I think of it, it might also be the call to StripAddress (in the macro `RETRO68_GET_DISPLACEMENT_STRIP` , used at the beginning of `Retro68Relocate` and defined in `Retro68Runtime.h`), I don't know what system version first supported that call.

Error 12 is something strange, if you're not using a debugger, there should be no breakpoints, so this probably means that we already jumped to the wrong address when we get this error...
At least I think that the `Debugger()` and `DebugStr()` calls that I might sometimes have used in place of "proper" error handling trigger an Error 10 if MacsBug is not installed, not an Error 12.

So I'd suggest to fix the error 10 first, that feels much easier.

**Comment by mdanh2002** [comment] 2017-03-24 14:38
Thanks. Let me work on it.

One question, I would like to use opendriver() found in Devices.h to write data to the serial port. The code compiles but fail with a linker error. This function seems to be in Interface.o in the Libraries folder on the MPW disk. Do you know how I should modify the CMake file for it to compile?

**Comment by mdanh2002** [comment] 2017-03-25 03:27
Found the issue. Need to call MacOpenDriver instead. Still investigating the original problem. Will update again if I find anything.

**Comment by mdanh2002** [comment] 2017-03-25 04:33
Not sure if this is a bug or if it is something which I haven't figured out, but many functions like SerReset or OpenDeskAcc declared in Devices.h were not present in the libraries when built, resulting in a linker error. I managed to get serial port output to work by sending the control codes directly after opening the serial port using MacOpenDriver. Quite troublesome.

**Comment by mdanh2002** [comment] 2017-03-25 05:30
I think I found another potential issue. I added my serial port output method to one of the sample from the MPW 3.1 disk (Sample.c - MultiFinder-Aware Simple Sample Application). The code compiles properly, but the generated application no longer runs on System 6.0.8 ("out of application memory" error is shown) and System 7.6.1 ("an error of type 15" is displayed). The error happens regardless of whether the newly added method is called in the code. 

I think it's because the newly added method has increased the code segment size of the generated application to above the 32KB limit imposed by the 68K Mac architecture. Without the added code, the generated application's CODE resource (as shown by ResEdit) contains 2 segment, ID = 0 with size 24 bytes and ID = 1 with size 10KB. With the added code, size of code resource with ID = 1 becomes 50KB, above the 32KB limit, which caused the error. The original sample code by MPW makes uses of #pragma segment to organize the codes into different segment (below 32KB), the names of which needs to be configured into the linker phase, to be loaded/unloaded dynamically at run-time as and when the respective code is needed. I do not think that the GCC compiler in Retro68 SDK recognizes the #pragma segment syntax.

I think the only way to bypass this is to put the extra code in a library, and edit the Makefile to include this library during the link phase. This technique is used in Browsy (https://github.com/clehner/Browsy) - the 68k web browser for System 6. I haven't tried this yet, but hopefully it will work.

**Comment by autc04** [comment] 2017-03-25 14:22
Code size can't be it, some of the included sample programs are way larger than 55KB.
Retro68K does not stick faithfully to that part of the 68K Mac architecture (that's actually a compiler-imposed limit, not a fundamental one). Basically, MPW used 16-bit offsets, for which the 68K has an efficient instruction, whereas gcc uses 32 bit absolute addresses. The "relocate" code is responsible for making all those addresses point to the right place (the OS chooses the address where the `CODE` is loaded).
So, putting everything in `CODE` 1 is fine (pragma segment is ignored), as long there is enough memory (check your `SIZE` resource and maybe add 100KB more). Linking things in .a files first should not make a difference.

As for the missing routines, that's issue #4. The problem is, I can't use MPW .o files like Interface.o (gcc's object file format is totally different), so the things from Interface.o have to be duplicated by hand in `libretro/glue.c`. That usually involves filling out a parameter block and calling the lower-level routine.

**Comment by mdanh2002** [comment] 2017-04-06 10:13
I got it working by using ResEdit to change the SIZE resource of the generated application. The original value is 58 00 00 00 8C 00 00 00 5C 00. I changed it to 58 00 00 00 FF 00 00 00 5C 00 and it works (the application can run). Is there a way to have the application automatically generated  with the correct SIZE resource without having to edit it manually?

**Comment by mdanh2002** [comment] 2017-04-06 10:25
I managed to do it properly. In Sample.r (the text resource file) there is a section that says:

resource 'SIZE' (-1) {
       ...
	kPrefSize * 1024,
	kMinSize * 1024	
}

where kPrefSize and kMinSize is declared in the header file as follows:

#define kMinSize	23				/* application's minimum size (in K) */
#define kPrefSize	35				/* application's preferred size (in K) */

These values declare the size of the application which will get bundled in the resources. Mac Finder uses these hard-coded fields to determine whether there is enough memory to start the application. I changed both of them to 100, recompile and the app works fine now. Stupid me, beginner to 68k programming. Many thanks.

**Comment by mdanh2002** [comment] 2017-04-07 09:30
Some observations on the original issues:

1. Error ID = 10 is most likely not caused by the called to SysEnvirons. That part of the code (starting line 204, libretrp/retro.c) only checks if the processor is 68040 or newer, and flushes the code cache if this the case. The Macintosh 512K uses a 68000, and the same error exists even if the suspected code is commented out.

2. The crash is most likely at line 133 (uint32_t headerOffsetInResource = ((uint32_t*)header)[-1];) or immediately after. It could have been a side effect (memory issues?) of calling StripAddress when it is not supported by the Finder version, but I am not so sure about this.

I will continue to investigate and update you again on this.

**Comment by mdanh2002** [comment] 2017-04-07 10:40
I confirmed it was due to StripAddress issue - see this http://www.bigmessowires.com/category/macintosh-floppy-emu/page/8/. The StripAddress trap is not supported on older System or ROM versions and calling it will cause a crash. Unfortunately the provided solution (replacing ONEWORDINLINE(0xA055) with 0x4E71 (NOP) in the declaration of StripAddress in MacMemory.h) does not work in Retro68 and doing so will result in ID = 02 (Address Error) instead. Just to share, I will try to find a way.

**Comment by autc04** [comment] 2017-04-07 11:07
Great!
Now you can try

    #define StripAddress(x) ((Ptr) ((unsigned long)(x) & 0x00FFFFFF))

We then still need to properly check whether StripAddress is available and call the real one if it is, because otherwise things will crash on System 7+ in 32-bit mode.

Also, you might need to comment out the SysEnvirons thing for now once we get that far, I don't know the minimum system version for that.

**Comment by mdanh2002** [comment] 2017-04-07 12:50
Thanks! That was it! The modification of StripAddress makes the generated program works fine on the stock Macintosh 512K! You are right that SysEnvirons will need to be commented out as well, for things to work. I will spend some time tomorrow to improve the code by using NGetTrapAddress to check if the functions are available before calling them so that the code can work well even in 32-bit mode.

**Comment by autc04** [comment] 2017-04-07 13:46
Great! Looking forward to a patch :-)

Just remember "the rules": no global variables, no function calls (except inline traps) before the call to `FlushCodeCache` for 68040 processors at the end.

**Comment by autc04** [comment] 2017-04-07 14:52
One problem you might run into: `NGetTrapÅddress` is one of those things implemented as a function call to `Interface.o`/`glue.c`.

And I'm not even sure the version in `glue.c` works for 64K ROMs (up to, I think, the Mac 512K); I think on those old Macs, it should use `GetTrapAddress` instead of the newer `GetOSTrapAddress` and `GetToolTrapAddress`. You should get away with only using `GetTrapAddress` directly, though.

**Comment by autc04** [comment] 2017-04-07 15:01
Correction: You can use `GetOSTrapAddress`, it seems to magically fall back to `GetTrapAddress` on old Macs.

**Comment by mdanh2002** [comment] 2017-04-09 08:19
Hi,

I spent one whole afternoon today trying various combinations, NGetTrapAddress, GetTrapAddress as well as GetOSTrapAddress on both SysEnvirons and StripAddress. To be able to debug effectively, I tried this inside my application (and not yet from retro.c) once it has started after compiling using the new GetStripAddress definition with the call to SysEnvirons (inside retro.c) commented out and checked the return address. Unfortunately, the usual implementation of comparing the returned trap with GetOSTrapAddress(_Unimplemented) to see whether the trap exists does not work on the Macintosh 512K with 64KB of RAM. The return address is different from the unimplemented trap, which means that the trap should be implemented, yet calling it will return an error. This applies for both the SysEnvirons and StripAddress traps.

To see if the trap-related methods are indeed working properly, I tried to call GetOSTrapAddress with the SetDefaultStartup trap on System 6.0.8 (not supported since there is no Startup control panel) and System 7.5.5 (supported with the Startup control panel). The results are expected - the method returned Unimplemented on 6.0.8 and correct addresses for 7.5.5. This means the method itself is working properly on later systems with 128KB RAM and there is probably a problem on 64KB of RAM.

So I guess we can't fix this by checking for trap existence. Maybe check for the ROM size and assume that 
SysEnvirons and StripAddress are not supported if we detect 64KB of RAM. I will see how this can be done.

**Comment by mdanh2002** [comment] 2017-04-09 08:23
I would like to add that other than the trap issues, basic apps with dialogs and menus built using Retro68 seem to work fine on the Macintosh 512K. I can even get my app to write to the serial port properly on this Mac. Unfortunately the sample console app (build using RetroConsole) doesn't run on the Macintosh 512K. Its size is bigger than the 800K floppy disk (almost 920K due to the added library size), and even with the HD20, it will fail to run (not enough memory). Is there a way to reduce the size of the RetroConsole library?

**Comment by autc04** [comment] 2017-04-10 08:25
The culprit is `libstdc++`'s implementation of locales. It's huge.
The actual code for libRetroConsole and all the parts of the C++ standard library that it actually uses is in the two-digit kilobytes range.
It used to be the case that the locale code only got pulled in when the iostream part of the library was used, but apparently after some GCC update it now even gets pulled in all the time, even though that code is never really used.

I can think of three approaches to solve this:

1. Update to the newest version of GCC/libstdc++ and check if this is already fixed - some developer of embedded software might have already complained.

2. Hack `libstdc++` for a fix/workaround.

3. See if `libc++` (https://libcxx.llvm.org/) can be used instead of `libstdc++` and if that is more compact.

4. Implement `CODE` segmentig; manually move all unused code to a separate `CODE` resource that is never loaded.

5. Reimplement `libRetroConsole` in plain C, but that doesn't fix the problem that C++ code doesn't run on the 512K...

None of 1-4 is exactly "easy" to do...

**Comment by mdanh2002** [comment] 2017-04-10 10:32
Thanks for the hints. Let me try on an old version of GCC and on the latest version of GCC to see if the file  size makes a difference. Alternatively, just a thought, maybe manually modify libretrocrt.a after building to remove the stuff that we don't need and use that for the compilation. 

I also got the trap detection to work. We must first detect which type of ROM is used by examining the word value at the ROM85 position (0x028E). If the value is positive, a 128K ROM is used and we can proceed to check for the existence of the traps using GetOSTrapAddress. If the value is zero or negative, a 64K ROM is used and the SysEnvirons and StripAddress traps won't be available. This is needed because GetOSTrapAddress may not function as designed on 64K ROM for unimplemented traps. 

See this http://www.mac.linux-m68k.org/devel/macalmanac.php for the list of fixed memory locations where other useful information can be retried.

I will be releasing a patch to fix the issue using this approach shortly.

**Comment by autc04** [comment] 2017-04-10 13:00
Upgrading to a new version of GCC is nontrivial, because you'd have to port all my patches (I might do that when I have the time).
As for old versions, that is doable, just look at the Retro68 commit history and check out an old version of Retro68.

As for manually modifying the .a, that won't work. `libRetroConsole.a` is tiny. It only references a few other small parts of libstdc++, which in turn reference lots of other parts. The big parts only get followed when GNU ld is resolving the references during linking.



Ah... ROM85... I dimly remember hearing about that, but it was before my time. Thanks!

**Comment by mdanh2002** [comment] 2017-04-10 13:26
The patch can finally be found here at http://toughdev.com/public/retro68k_mac512k.patch

I made 2 changes:

1. Change Retro68Runtime.h to add RETRO68_GET_DISPLACEMENT_STRIP2 and use it on old system without StripAddress:

#define StripAddress2(x) ((Ptr) ((unsigned long)(x) & 0x00FFFFFF))
#define RETRO68_GET_DISPLACEMENT_STRIP2(DISPLACEMENT) \
	_RETRO68_GET_DISPLACEMENT(DISPLACEMENT, StripAddress2)

2. Change method Retro68Relocate() in relocate.c. The modified method now checks for the ROM type and whether StripAddress and SysEnvirons are available before calling them.

With this change, the compiled sample apps now works fine on all Mac that I have: Macintosh 512K (OS 3.2 Finder 5.3). Macintosh SE (System 6.0.8), Macintosh SE/30 (System 7.1 with MODE32), Powerbook 165 (System 7.5.5), Powerbook 5300cs (System 8.1) and Powerbook G3 (System 9.0.4). So I guess Retro68K should be good now.

Btw, the reason why GetOSTrapAddress doesn't return 'unimplemented' for those traps is because it only takes the last 8 bits of the OS traps on 64K ROMs. Since there were no trap number overlaps on the original 64K ROM, this works. However, when we build using MPW 3.5 header files and run on the old ROMs, many more traps supported by newer ROMs are also present in the headers. The last few bits of some of these traps (which are used by GetOSTrapAddress for checking) could be the same, hence GetOSTrapAddress may return the address for another trap which is present on the 64K ROM that has the same bits as the one we are enquiring on (which may not be present).

Another comment that I have is that the Raytracer sample fails to build (missing header), causing the build process of Retro68K to terminate prematurely. I worked around this by replacing the content of the RayTracer sample app with the HelloWorld app. I guess this is due to header incompatibilities. I am using MPW 3.5 header files.

Also, it might be good if the first few steps of the build could check if the important required packages are present. Currently, if the 'autoconf' package is not present, the Retro68 build will fail towards the end of the long build process.

Finally, just a question, can the generated debug symbols be used in anyway? I am using your SDK with CodeLite and PCE/macplus emulator to develop an integrated environment for 68K Mac. Would be good if the debug symbols in GDB can be used to facilitate debugging.

**Comment by mdanh2002** [comment] 2017-04-11 10:04
My full review on Retro68 can be found here:

http://www.toughdev.com/content/2017/03/exploring-retro68-gcc-based-sdk-for-68k-macintoshes/

In the article I documented the issues with Retro68 I faced for the past few weeks, and summarized the solutions :)

I will also be creating a VirtualBox image that uses Retro68, pce/macplus and CodeLite as a modern integrated development for 68k Mac. Will provide a link here when that is done for those who are interested. :)

**Comment by autc04** [comment] 2017-04-11 19:27
Thanks a lot for the patch.

I took the liberty of renaming `StripAddress2` to `StripAddress24` to indicate that it's the 24-bit-only version.

And I like that blog post.
Two technical comments/corrections:
* Retro68 does not generate a `'CODE' 256` resource, only IDs 0 and 1. Where does that resource come from? Does your emulator have a virus?
* `glue.c` code will not be required for most QuickDraw or Toolbox calls, as those are implemented as Traps. File Manager & Device Manager are the most problematic areas; for these, the traps are usually the parameter-block based versions, with the other variants implemented as small wrappers in `Interface.o`. Basically, everything that has a `ONEWORDINLINE` (or `TWOWORDINLINE`, etc.) declaration in Apple's headers will just work.


> debug symbols

The full debug symbols can't be used yet (getting gdb working for cross-debugging classic macs or emulators - that would be another big project...), but you can run tools like `addr2line` and `objdump` on the `*.flt.gdb` files.

**Comment by autc04** [comment] 2017-04-11 20:02
Yes, check your emulator for an [`nVIR`|https://en.wikipedia.org/wiki/NVIR] infection.

**Comment by mdanh2002** [comment] 2017-04-12 09:20
Thanks for the comments. I have updated the articles with your inputs. You are right that my System 6.0.8 emulator is infected with the nVIR virus. No wonder I sometimes heard "Don't panic" when the machine was powered on. Will perform a virus scan on those emulators this weekend to clean up the infections.

As for debugging, PCE/macplus does have some support for assembly-level debugging (mini disassembler, step over, memory dump, read/write register values). I tried and it did work with Retro68 apps, albeit not very useful since I can only step through the disassembled code instruction by instruction, and not the original code.  Maybe when I am free I will see how I can change it to work with your debug symbols and make debug more user-friendly, showing the original C code (and not 68K assembly instructions) if possible.

**Closed** 2017-10-15 09:19 UTC

**Comment by mdanh2002** [comment] 2019-06-14 14:25
I know that this issue has been closed but here is an update after almost two years. After some experimenting, Retro68 together with CodeLite and pce/macplus emulator can form a very good 68k development environment. I wrote an article about this here http://www.toughdev.com/content/2018/12/developing-68k-mac-apps-with-codelite-ide-retro68-and-pce-macplus-emulator/ which provides detailed instructions. There is also a VirtualBox image with everything set up as well as a YouTube demo video where you can see how Retro68 is being used with pce/macplus to develop 68k Mac apps nicely. Even autocomplete is also supported simply by telling CodeLite to parse the CIncludes and RIncludes folders. Will be great if you can try it out and let me know what you think.

**Comment by autc04** [comment] 2019-06-16 18:46
Wow, looks great!
