### ISSUE TITLE
App crashes - 'SIZE' resource is ignored

### ISSUE THREAD

**Issue by antscode** [autc04/Retro68#43] opened 2018-01-08 03:30 UTC
[jsontest.zip](https://github.com/autc04/Retro68/files/1610538/jsontest.zip)
I've tried to figure this one out myself but I'm at a loss. With the latest build of Retro68, I'm now getting a strange issue when linking to an external C++ library and also referencing other C++ code in my app.

I created a simple test app, and the issue is highlighted in the cmake file:

```CMake
cmake_minimum_required(VERSION 2.8)

add_application(JsonTest
	JsonTest.cpp
	size.r
	# jsoncpp.cpp # Un-commenting this file crashes the app on launch - even if there are no code references to it, but only if the below libraries are also linked
)

# If I don't link to these libraries, then the above jsoncpp.cpp file works fine - the app only crashes when both are enabled
target_link_libraries(JsonTest MacHTTP mbedtls mbedx509 mbedcrypto MacTCPHelper)
```

I've attached a sample app, but it involves building & installing a few dependent libraries ([MacTCPHelper](https://github.com/antscode/MacTCPHelper), [mbedtls-Mac-68k](https://github.com/antscode/mbedtls-Mac-68k) and [MacHTTP](https://github.com/antscode/MacHTTP) - in that order)

The only other thing worth mentioning is that on my new PC I've built Retro68 without PPC support.

Hoping you can help?

**Comment by autc04** [comment] 2018-01-08 08:24
I can confirm that this is almost certainly "my fault".

Retro68's initialization code gets confused and crashes with an assertion failure before `main` is even entered. Stay tuned...

**Comment by antscode** [comment] 2018-01-08 08:35
Thank you. If it helps, it'll be due to a commit on or after 5 Dec...

**Comment by autc04** [comment] 2018-01-08 09:01
Okay, it's a simple problem after all: your program only has 1MB of memory, but 1.2MB of code.

It's still my fault, though, because you did specify a larger memory size, and that currently gets ignored because I broke it. Retro68 provides a default `SIZE` resource with a partition size of 1MB; the intent was for your `SIZE` resource to take precedence, but I broke that, so you always get 1MB.
There are also two distinct places where I should have checked for errors so this problem might have been more obvious.

Workaround: after compiling, increase preferred & minimum memory sizes from the Finder's "Get Info" dialog box on a Mac.

**Comment by antscode** [comment] 2018-01-08 09:28
Thank you! That makes sense because increasing the memory requirements in my size resource has often fixed problems like this.

As an aside, I would love to know how you debug your Mac apps - my debugging consists of commenting out lines of code until things start working again...

**Comment by autc04** [comment] 2018-01-09 00:04
Should be fixed now. The bug was introduced last weekend, when I fixed things for the WDEF sample...

On Debugging: one word - MacsBug.
I've started compiling some hints on the wiki: https://github.com/autc04/Retro68/wiki/Debugging

**Closed by autc04** 2018-01-09 00:04 UTC

**Comment by antscode** [comment] 2018-01-09 00:09
Thank you - and thanks so much for the debugging info.
